### DISCUSSION TITLE
在主题官方站点展示你的网站 / Show Your Website on the Official Theme Site

### DISCUSSION THREAD

**Discussion by mirai-mamori** [Fuukei/docs_site#1] [Announcements]
![showyoursite](https://s.nmxc.ltd/fuukei_docs/sakurairo/sysotos.webp)

如果您正在使用 `Sakurairo 主题`，你可以在这里留下你的站点链接。
主题团队会把它加入示例站点中！
 
 ## 格式
```yaml
"name": "明日が来ると", 
"url": "https://kiseki.blog", 
"avatar": "https://s.nmxc.ltd/sakurairo_vision/asuhe/avatar.jpg", 
"desc": "信じてること自体が希望なんだ" 
"mail":"me@hareru.org"
```

"name":  ——》# 最好不要太长，控制在八个中文字符宽度内
"url":      ——》 # 站点链接
"avatar": ——》# 你的头像链接，请确保它为正方形或圆形。
"desc":   ——》# 简单描述一下你的站点、或者你喜欢的句子
"mail"：——》# 留一个主题开发者可以给你发通知的邮箱

 其他你想要说的话（畅所欲言～）
 
## 注意:

 * ①：为了保证 周边文档页面 的展示型、表现性以及有效性，周边文档页面 目前只接受建站时间＞3个月的的站点，原创且有效内容帖子＞10个。
 * ②：为了保证 周边文档页面 的加载速度，周边文档页面 将会同步修订图片，图片将会启用相关域名为你展示头像。
 * ③：为了保证 周边文档页面 的躺平性，周边文档页面 不收录含有违法违纪、侵权等类型的站点。
 * ④：为了保证我们能联系到你，请在申请的时候留下您的相关邮箱（不留默认拒绝，除非做得好，Fuukei 团队主动与你联系）。
 * ⑤：请悉知，Sakurairo 原则上不接受去除了版权提示的站点申请（除非你做得很好、有特批、对主题贡献很高等情况）。

Fuukei 团队保留对你的申请一票否决的权利。

## 支持我们：
[<img src="https://s.nmxc.ltd/sakurairo_vision/@3.0/readme/afdian.webp" alt="afdian" height="50px">](https://afdian.com/a/mamori)
[<img src="https://s.nmxc.ltd/sakurairo_vision/@3.0/readme/liberapay.webp" alt="liberapay" height="50px">](https://liberapay.com/furina/donate)
[<img src="https://s.nmxc.ltd/sakurairo_vision/@3.0/readme/unifans.webp" alt="unifans" height="50px">](https://app.unifans.io/c/somekawahitomi)
